### ISSUE TITLE
the path of cropped aligned

### ISSUE THREAD

**Issue by Jesayy** [sucv/ABAW3#7]
Hello, while uploading the dataset, I noticed that there are two folders in the "cropped_aligned" directory: "cropped_aligned" and "cropped_aligned_new_50_vids", however, in your code, it seems that only the "cropped_aligned" folder is being used. I'm not entirely sure which folder should be used. If possible, could you provide the dataset folder structure ? Thank you very much!!!

**Comment by sucv** [comment]
Please manually copy everything under "cropped_aligned", there should be like 594 folder there containing every trials.

**Comment by Jesayy** [comment]
could you provide the dataset folder structure ?thanks

**Comment by sucv** [comment]
Hi Jesayy,

Please see [here](https://github.com/sucv/ABAW2#step-three-configure-)
